### ISSUE TITLE
Validate certificate of https://downloads.linux.hpe.com - stores the RPM GPG keys

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-hp-spp#1]
In https://github.com/CSC-IT-Center-for-Science/ansible-role-hp-spp/blob/master/tasks/redhat.yml#L4

we get the RPM GPG keys over http.

With https:// you get this error:

<pre>
msg: Failed to validate the SSL certificate for downloads.linux.hpe.com:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
</pre>

**Comment by julianrutten** [comment]
Same here, seems like HP switched to a new domain for their repository but their certificate is incomplete.

**Comment by chewi** [comment]
[HP scores an F!?](https://www.ssllabs.com/ssltest/analyze.html?d=downloads.linux.hpe.com) Unbelievable.

**Comment by martbhell** [comment]
I now get an A from sslabs and if I test with fetching them over https it works. 
However, the benefits for doing this seems small. Closing this issue and keeping as http.
